from selenium.webdriver.common.by import By

class AuthLocators:
    TAB_PHONE = (By.ID, 't-btn-tab-phone')
    ACTIVE_TAB_PHONE = (By.XPATH, '//div[@id="t-btn-tab-phone" and @class="rt-tab rt-tab--small rt-tab--active"]')
    TAB_MAIL = (By.ID, 't-btn-tab-mail')
    TAB_LOGIN = (By.ID, 't-btn-tab-login')
    TAB_LS = (By.ID, 't-btn-tab-ls')
    AUTH_LOGIN = (By.ID, "username")
    AUTH_PASS = (By.ID, "password")
    AUTH_BTN = (By.ID, "kc-login")
    BTN_VK = (By.ID, "oidc_vk")
    BTN_OK = (By.ID, "oidc_ok")
    BTN_MA = (By.ID, "oidc_mail")
    BTN_YA = (By.ID, "oidc_ya")
    BTN_FORGOT_PASSWORD = (By.ID, "forgot_password")
    PASS_RECOVERY = (By.CLASS_NAME, "card-container__title")
    REGISTER_LINK = (By.ID, "kc-register")
    CARD_OF_AUTH = (By.CLASS_NAME, 'card-container__wrapper')
    TAB_MENU = (By.XPATH, "//div[@class='rt-tabs rt-tabs--orange rt-tabs--small tabs-input-container__tabs']")
    PAGE_RIGHT = (By.ID, 'page-right')
    PAGE_LEFT = (By.ID, 'page-left')
    ERROR_MESSAGE = (By.XPATH, '//span[@id="form-error-message"]')
    BUTTON_ENTRY_VK = (By.CLASS_NAME, "marked-element")

class RegLocators:
    FIRST_NAME = (By.XPATH, '//*[@id="page-right"]/div[1]/div[1]/div[1]/form[1]/div[1]/div[1]/div[1]/input[1]')
    LAST_NAME = (By.XPATH, '//*[@id="page-right"]/div[1]/div[1]/div[1]/form[1]/div[1]/div[2]/div[1]/input[1]')
    MAIL_REG = (By.ID, 'address')
    ADR_REG = (By.XPATH, "//*[contains(text(),'Регион')]")
    PASS_REG = (By.ID, 'password')
    PASS_REG_CONFIRM = (By.ID, 'password-confirm')
    BTN_REG = (By.NAME, 'register')
    CARD_OF_REG = (By.CLASS_NAME, 'card-container__wrapper')
    USER_AGREEMENT = (By.XPATH, '//*[@id="page-right"]/div[1]/div[1]/div[1]/form[1]/div[5]/a[1]')
    MAIL_CONFIRM = (By.XPATH, '//*[@id="page-right"]/div[1]/div[1]/h1[1]')
    MASSAGE_FIRST_NAME = (By.XPATH, '//*[@id="page-right"]/div[1]/div[1]/div[1]/form[1]/div[1]/div[1]/span[1]')
    MASSAGE_LAST_NAME = (By.XPATH, '//*[@id="page-right"]/div[1]/div[1]/div[1]/form[1]/div[1]/div[2]/span[1]')
    CONTAINER_FIRST_NAME = (By.XPATH,'//*[@id="page-right"]/div[1]/div[1]/div[1]/form[1]/div[1]/div[1]/div[1]/input[1]')
    CONTAINER_LAST_NAME = (By.XPATH, '//*[@id="page-right"]/div[1]/div[1]/div[1]/form[1]/div[1]/div[2]')